-name: Deploy to Tomcat
 host: web
 become: yes
 tasks:
 	-name: Copy WAR file to Tomcat
 	copy:
	 	src: "/var/snap/jenkins/5022/workspace/MavenAnsible2/target/MavenAnsible.war"
	 	dest: 
	 	remote_src: mo
	 -name: Restart Tomcat
	 stsyemmd:
	 	name: tomcat
	 	state: restarted
 
